name: main

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    permission:
      packages: write
    steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: nagin:latest
          